### ISSUE TITLE
i cant subscribed topic

### ISSUE THREAD

**Issue by wangzhengqing** [tenzir/threatbus#62]
### Observed Behavior
i have install threatbus threatbus-zeek threatbus-misp threatbus-inmem. 
i can't subscribed to p2p_topic

1. i don't have zmq on my centos. if i setup       
   zmq:
        host: localhost
        port: 50000
can it work?

2. if i want to use kafka.
      kafka:
         topics:
         - misp_attribute
         poll_interval: 1.0
         config:
           bootstrap.servers: "x.x.x.x:9092"
           group.id: "threatbus"
           auto.offset.reset: "earliest"
i get error :    Kafka error: KafkaError{code=UNKNOWN_TOPIC_OR_PART,val=3,str="Subscribed topic not available: misp_attribute: Broker: Unknown topic or partition"}

### Environment Context
zeek version 3.0.8
full config.yml:

logging:
  console: true
  console_verbosity: DEBUG
  file: false
  file_verbosity: DEBUG
  filename: threatbus.log

plugins:
  backbones:
     inmem:

  apps:
    zeek:
      host: "localhost"
      port: 47761
      module_namespace: Tenzir
    misp:
      api:
        host: http://x.x.x.x
        ssl: false
        key: xxxxxxxxxxxxxxxxxxxx
      zmq:
        host: localhost
        port: 50000
\#      kafka:
\#        topics:
\#        - misp_attribute
\#        poll_interval: 1.0
\#        config:
\#          bootstrap.servers: "x.x.x.x:9092"
\#          group.id: "threatbus"
\#          auto.offset.reset: "earliest"

**Comment by 0ortmann** [comment]
Hi @wangzhengqing

MISP exposes it's own ZMQ endpoint and the Threat Bus plugin binds to it. You won't need to have a dedicated ZMQ endpoint on your machine. Kafka is a separate application. If you want to use Kafka, you first need to set up a Kafka cluster, then connect MISP and Threat Bus to it.

Note that Threat Bus only can use *one* channel to communicate with MISP, so you either use MISP ZMQ or a dedicated Kafka endpoint. For ease of use, I recommend starting with the built-in ZMQ endpoint in MISP.

**Comment by wangzhengqing** [comment]
Hi @0ortmann 

when i use threatbus.zeek to start subscrib p2p_topic.  but always can't subscribed to p2p_topic.

start threatbus:
$ threatbus -c config.yml
2020-11-10 09:59:39 INFO     [threatbus] Starting plugins...
2020-11-10 09:59:39 INFO     [threatbus_inmem.plugin] In-memory backbone started.
2020-11-10 09:59:39 INFO     [threatbus_inmem.plugin] Adding subscription to: threatbus/snapshotrequest
2020-11-10 09:59:39 INFO     [threatbus_inmem.plugin] Adding subscription to: threatbus/snapshotenvelope
2020-11-10 09:59:40 INFO     [threatbus_zeek.plugin] Zeek plugin started
WARNING [api.py:136 - __init__() ] The version of PyMISP recommended by the MISP instance (2.4.134) is newer than the one you're using now (2.4.133). Please upgrade PyMISP.
2020-11-10 09:59:40 INFO     [threatbus_inmem.plugin] Adding subscription to: threatbus/sighting
2020-11-10 09:59:40 INFO     [threatbus_misp.plugin] MISP plugin started


start threatbus.zeek:
$ zeek -i ens224 -C threatbus.zeek 
listening on ens224

./threatbus.zeek, line 120: subscribing to management topic threatbus/manage
./threatbus.zeek, lines 121-122: reporting noisy intel at 100 matches/sec
./threatbus.zeek, lines 136-137: peering to threatbus at 127.0.0.1:47761/tcp
1604973640.496772 ./threatbus.zeek, line 109: threatbus peered


^C1604974645.390012 received termination signal
1604974645.390012 28001 packets received on interface ens224, 0 dropped
1604974645.390012 ./threatbus.zeek, line 149: unsubscribing from p2p_topic

**Comment by 0ortmann** [comment]
Hi @wangzhengqing

can you please tell me a bit more about your setup? I need to know the following:

- What OS do you use to run Threat Bus and Zeek?
- What is the version of Threat Bus and the installed plugins?
- What Zeek version do you use?
- What is the version of the installed [zeek/broker](https://github.com/zeek/broker) bindings?

**Comment by wangzhengqing** [comment]
Hi, @0ortmann 

MISP used vmdk  run at EXSI  and version 2.4.134
ZEEK OS:  centos 7.8
Python：3.8
pip3: 20.2.4
ZEEK: 3.0.8
pip3 list | grep threatbus
threatbus         2020.10.29
threatbus-inmem   2020.10.29
threatbus-misp    2020.10.29
threatbus-zeek    2020.10.29
broker：1.4.0

**Comment by 0ortmann** [comment]
@wangzhengqing I think the problem is that Zeek and Threat Bus cannot communicate via `broker` because of a version mismatch. You use Zeek version 3.0.8 and broker 1.4.0. From the [release notes of broker 1.4.0](https://github.com/zeek/broker/releases/tag/v1.4.0):

> Note: Releases in the v1.4.x series are aligned for use in Zeek v3.2.x and do not support Zeek v3.0.x (Broker v1.2.x are meant to be used for that Zeek LTS release branch).

You need to either update Zeek or downgrade broker.

**Comment by wangzhengqing** [comment]
Hi @0ortmann 

now it works.  

when i write to local.zeek
@load somepath/threatbus.zeek

and run : zeekctl deploy

it doesn't work again.
Does it have to use alone?

**Comment by 0ortmann** [comment]
Hi @wangzhengqing

The option `zeek -C` already disables checksums checking, so you don't need to set `ignore_checksums = T;`.

From the help menu:
```
zeek -h
zeek version 3.2.0
usage: zeek [options] [file ...]
usage: zeek --test [doctest-options] -- [options] [file ...]
...
    -C|--no-checksums              | ignore checksums
...
```

However, that issue should be unrelated to Threat Bus.

**Comment by mavam** [comment]
@wangzhengqing I'm trying to understand the problem a little better. Is it that Threat Bus runs in local mode but not in cluster mode?

**Comment by wangzhengqing** [comment]
@mavam 
when i run 
`zeek -i en111 -C threatbus.zeek`
it worked

when i add threatbus.zeek to $PREFIX/zeek/share/zeek/site/local.zeek
`@load mypath/threatbus.zeek`
`zeekctl deploy`

it doesn't work again

**Comment by mavam** [comment]
Apologies for the delay, @wangzhengqing.

I have a hunch that this issue is related to the conditional execution of Zeek cluster code. Could I ask you to replace one line of Zeek code and let us know whether it works then?

If you replace [line 132 of apps/zeek/threatbus.zeek](https://github.com/tenzir/threatbus/blob/b7ffeee32ea4c0784aa6f3eb4aba9c2d84c37210/apps/zeek/threatbus.zeek#L132) from


```zeek
@if ( ! Cluster::is_enabled() )
```

to

```zeek
@if ( ! Cluster::is_enabled()
      || Cluster::local_node_type() == Cluster::MANAGER )
```

does the error still persist?

**Comment by wangzhengqing** [comment]
Hi @mavam 

thank you very match. now it worked.
